spring:
  datasource:
    username: root
    password: 45185947wuyi-
    url: jdbc:mysql://localhost:3306/mall_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-coupon
management:
  endpoint:
    health:
      show-details: always
    httptrace:
      enabled: true
  server:
    port: 8998
  endpoints:
    web:
      exposure:
        include: "*"

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 7000

coupon:
  user:
    name: zhangsan
    age: 20
